from __future__ import annotations

from datetime import datetime
from zoneinfo import ZoneInfo


AGENTS = [
    {
        "name": "Master Orchestrator",
        "group": "Core",
        "icon": "compass",
        "tone": "orange",
        "description": "Routes missions, coordinates specialists, and keeps every output aligned.",
        "metric": "100% routing health",
        "status": "Active",
    },
    {
        "name": "AI Bartender",
        "group": "Guest Experience",
        "icon": "martini",
        "tone": "green",
        "description": "Recommends tequila, cocktails, tastings, and sponsor-brand pairings.",
        "metric": "125 active chats",
        "status": "Active",
    },
    {
        "name": "AI Chef",
        "group": "Guest Experience",
        "icon": "chef",
        "tone": "green",
        "description": "Guides food pairings, menu notes, flavor bridges, and dietary care.",
        "metric": "93 pairings",
        "status": "Active",
    },
    {
        "name": "Tour Guide",
        "group": "Guest Experience",
        "icon": "pin",
        "tone": "green",
        "description": "Handles wayfinding, floor navigation, room info, timing, and accessibility.",
        "metric": "58 tours in progress",
        "status": "Active",
    },
    {
        "name": "Cultural Storyteller",
        "group": "Guest Experience",
        "icon": "agave",
        "tone": "green",
        "description": "Shares tequila, agave, craft, music, art, and cultural education.",
        "metric": "24 story moments",
        "status": "Active",
    },
    {
        "name": "Guest Concierge",
        "group": "Guest Experience",
        "icon": "concierge",
        "tone": "green",
        "description": "Answers FAQs, support needs, hospitality replies, and escalations.",
        "metric": "312 interactions",
        "status": "Active",
    },
    {
        "name": "Ticketing Agent",
        "group": "Commerce",
        "icon": "ticket",
        "tone": "gold",
        "description": "Supports admissions, upgrades, packages, group sales, and Tixr flows.",
        "metric": "1,248 tickets sold",
        "status": "Active",
    },
    {
        "name": "Merch and Bottle Sales",
        "group": "Commerce",
        "icon": "bottle",
        "tone": "gold",
        "description": "Guides product discovery, retail questions, bundles, and checkout paths.",
        "metric": "$26.4K revenue",
        "status": "Active",
    },
    {
        "name": "Passport and Missions",
        "group": "Commerce",
        "icon": "qr",
        "tone": "gold",
        "description": "Manages check-ins, QR scans, rewards, and guest progression.",
        "metric": "832 redemptions",
        "status": "Active",
    },
    {
        "name": "CRM and Lead Capture",
        "group": "Commerce",
        "icon": "user",
        "tone": "gold",
        "description": "Maintains profiles, consent, preferences, lead capture, and sponsor data.",
        "metric": "78 sponsor leads",
        "status": "Active",
    },
    {
        "name": "VIP Upsell Agent",
        "group": "Commerce",
        "icon": "crown",
        "tone": "gold",
        "description": "Shapes premium offers, reservations, hosted experiences, and VIP follow-up.",
        "metric": "37 premium offers",
        "status": "Active",
    },
    {
        "name": "Schedule Agent",
        "group": "Operations",
        "icon": "calendar",
        "tone": "teal",
        "description": "Coordinates programming, staffing, room timing, and run-of-show plans.",
        "metric": "42 events today",
        "status": "Active",
    },
    {
        "name": "Analytics Agent",
        "group": "Operations",
        "icon": "chart",
        "tone": "teal",
        "description": "Turns guest flow, sales, sentiment, and sponsor data into decisions.",
        "metric": "Live performance",
        "status": "Active",
    },
    {
        "name": "Feedback Agent",
        "group": "Operations",
        "icon": "chat",
        "tone": "teal",
        "description": "Captures surveys, ratings, issues, sentiment, and guest recovery actions.",
        "metric": "4.7 avg sentiment",
        "status": "Active",
    },
    {
        "name": "Sponsor Intelligence",
        "group": "Operations",
        "icon": "handshake",
        "tone": "teal",
        "description": "Builds activation insights, partner reports, and sponsor-ready recaps.",
        "metric": "18 active sponsors",
        "status": "Active",
    },
    {
        "name": "Internal Ops Agent",
        "group": "Operations",
        "icon": "gear",
        "tone": "teal",
        "description": "Triages issues, finds SOPs, logs incidents, and supports staff handoffs.",
        "metric": "All systems normal",
        "status": "Active",
    },
    {
        "name": "Research Agent",
        "group": "Creative Studio",
        "icon": "search",
        "tone": "blue",
        "description": "Researches trends, competitors, tequila category signals, and activation ideas.",
        "metric": "12 reports running",
        "status": "Active",
    },
    {
        "name": "Docs Agent",
        "group": "Creative Studio",
        "icon": "doc",
        "tone": "blue",
        "description": "Creates briefs, SOPs, plans, sponsor recaps, PDFs, Markdown, and DOCX.",
        "metric": "7 pending approvals",
        "status": "Active",
    },
    {
        "name": "Slides Agent",
        "group": "Creative Studio",
        "icon": "slides",
        "tone": "blue",
        "description": "Builds sponsor decks, pitch decks, recap decks, and PowerPoint exports.",
        "metric": "5 decks in progress",
        "status": "Active",
    },
    {
        "name": "Image Agent",
        "group": "Creative Studio",
        "icon": "image",
        "tone": "blue",
        "description": "Creates campaign visuals, ad creative, lifestyle images, and art assets.",
        "metric": "23 assets generated",
        "status": "Active",
    },
    {
        "name": "Video Agent",
        "group": "Creative Studio",
        "icon": "video",
        "tone": "blue",
        "description": "Produces teasers, promos, social clips, recaps, captions, and edits.",
        "metric": "4 videos rendering",
        "status": "Active",
    },
]


ACTIVITY = [
    {"agent": "Research Agent", "event": "Completed Miami event trend scan", "time": "12m ago", "tone": "blue"},
    {"agent": "Slides Agent", "event": "Generated sponsor recap deck v2", "time": "28m ago", "tone": "blue"},
    {"agent": "Image Agent", "event": "Created campaign hero visual", "time": "45m ago", "tone": "gold"},
    {"agent": "Docs Agent", "event": "Updated partnership agreement", "time": "1h ago", "tone": "green"},
    {"agent": "Analytics Agent", "event": "Refreshed sales and sentiment report", "time": "2h ago", "tone": "teal"},
]


def dashboard_state() -> dict:
    now = datetime.now(ZoneInfo("America/New_York"))
    return {
        "event": {
            "name": "TequilaTown AgentSwarm",
            "venue": "4710 Northwest 37th Avenue, Miami, FL 33142",
            "status": "Live",
            "localTime": now.strftime("%A, %b %-d - %-I:%M %p ET"),
            "tagline": "Your intelligent crew for the TequilaTown experience.",
        },
        "health": {
            "performance": 100,
            "tasksToday": 32,
            "completed": 18,
            "timeSaved": "2.4h",
            "activeAgents": f"{len(AGENTS)}/{len(AGENTS)}",
            "sentiment": "4.7/5",
            "sponsorLeads": 78,
            "ticketRevenue": "$26.4K",
        },
        "agents": AGENTS,
        "activity": ACTIVITY,
        "quickActions": [
            {
                "label": "New Mission",
                "description": "Create and route a swarm task",
                "tone": "green",
                "prompt": "Route a TequilaTown mission to the right specialist agents.",
            },
            {
                "label": "New Project",
                "description": "Launch a campaign workspace",
                "tone": "green",
                "prompt": "Launch a new TequilaTown campaign workspace with owners, assets, and next steps.",
            },
            {
                "label": "Upload Brief",
                "description": "Add files to the knowledge base",
                "tone": "gold",
                "prompt": "Summarize this brief, extract tasks, and route follow-up work.",
            },
            {
                "label": "Swarm Report",
                "description": "Generate a performance report",
                "tone": "blue",
                "prompt": "Create a TequilaTown AgentSwarm performance report with risks and next actions.",
            },
        ],
    }
